# 데이터프레임의 다양한 응용
* **Series객체.apply(매핑함수)** : 시리즈 원소에 함수 매핑 <br>
  인자로 전달하는 매핑 함수에 시리즈의 **모든 원소를 하나씩 입력**하고 함수의 리턴값을 돌려받는다.

In [1]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[:, ['age','fare']]
df['ten'] = 10
print(df.head())

Bad key text.latex.unicode in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 112 ('text.latex.unicode : False # use "ucs" and "inputenc" LaTeX packages for handling')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key text.dvipnghack in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 127 ("text.dvipnghack : None      # some versions of dvipng don't handle alpha")
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.frameon in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 430 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key nbagg.transparent in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 433 ('nbagg.transparent: True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key pgf.debug in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 453 ('pgf.debug           : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 484 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 485 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_path in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 516 ('animation.mencoder_path: mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_args in file /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 519 ('animation.mencoder_args:          # Additional arguments to pass to mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/jihyunyang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [2]:
def add_10(n):
    return n+10

def add_two_obj(a, b):
    return a+b

print(add_10(10))
print(add_two_obj(10,10))

20
20

In [3]:
sr1 = df['age'].apply(add_10) # n=df['age']의 모든 원소
print(sr1.head())
print('\n')

sr2 = df['age'].apply(add_two_obj, b=10) # a=df['age']의 모든 원소,b=10
print(sr2.head())
print('\n')

sr3 = df['age'].apply(lambda x: add_10(x))  # x=df['age']
print(sr3.head())

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64


0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64


0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

* **데이터프레임 객체.applymap(매핑함수)** : 데이터프레임 원소에 함수 매핑 <br>
  인자로 전달하는 매핑 함수에 시리즈의 **모든 원소를 하나씩 입력**하고 함수의 리턴값을 돌려받는다.

In [4]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[:, ['age','fare']]
print(df.head())
print('\n')

def add_10(n):
    return n+10

df_map = df.applymap(add_10)
print(df_map.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [5]:
import pandas as pd
pd.DataFrame([[4,9]]*3, columns=['A','B'], index=['C','D','E'])

   A  B
C  4  9
D  4  9
E  4  9

## 시리즈 객체에 함수 매핑
* 데이터프레임의 각 열에 함수 매핑
* apply(axis=0) : 모든 열을 하나씩 분리하여 매핑함수의 인자로 각 열(시리즈)가 전달
* DataFrame 객체.apply(매핑함수, axis=0)

In [6]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.head())
print('\n')

# 함수는 시리즈를 입력받아서 시리즈를 리턴한다.
def missing_value(series):
    return series.isnull()

result = df.apply(missing_value, axis=0)
print(result.head())
print('\n')
#리턴값은 데이터프레임이다
print(type(result))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False


<class 'pandas.core.frame.DataFrame'>

In [7]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.head())
print('\n')

def min_max(x):
    return x.max() - x.min()

result = df.apply(min_max) #df의 각 열에(시리즈) min_max를 적용한다.
print(result)
print('\n')
print(type(result))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


age      79.5800
fare    512.3292
dtype: float64


<class 'pandas.core.series.Series'>

* apply(axis=1) : 모든 행을 하나씩 분리하여 매핑함수의 인자로 각 행(시리즈)가 전달
* DataFrame 객체.apply(매핑함수, axis=1)

In [8]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
df['ten'] = 10
print(df.head())
print('\n')


def add_two_obj(a, b):
    return a+b

df['add'] = df.apply(lambda x: add_two_obj(x['age'], x['ten']), axis=1)
print(df.head())

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10


    age     fare  ten   add
0  22.0   7.2500   10  32.0
1  38.0  71.2833   10  48.0
2  26.0   7.9250   10  36.0
3  35.0  53.1000   10  45.0
4  35.0   8.0500   10  45.0

In [9]:
df.describe().T  # describe를 .T로해서 보면 더 쉽게 보인다

      count       mean        std    min      25%      50%   75%       max
age   714.0  29.699118  14.526497   0.42  20.1250  28.0000  38.0   80.0000
fare  891.0  32.204208  49.693429   0.00   7.9104  14.4542  31.0  512.3292
ten   891.0  10.000000   0.000000  10.00  10.0000  10.0000  10.0   10.0000
add   714.0  39.699118  14.526497  10.42  30.1250  38.0000  48.0   90.0000

In [10]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.head())
print('\n')

def missing_value(x):
    return x.isnull()

def missing_count(x):
    return missing_value(x).sum()

def total_number_missing(x):
    return missing_count(x).sum()

result_df = df.pipe(missing_value) 
print(result_df.head())
print('\n')
print(type(result_df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False


<class 'pandas.core.frame.DataFrame'>

In [11]:
result_series = df.pipe(missing_count) 
print(result_series.head())
print('\n')
print(type(result_series))

age     177
fare      0
dtype: int64


<class 'pandas.core.series.Series'>

In [12]:
result_value = df.pipe(total_number_missing) 
print(result_value)
print('\n')
print(type(result_value))

177


<class 'numpy.int64'>

## 열 재구성
* 열 순서 변경

In [13]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[0:4, 'survived':'age']
print(df, '\n')

columns = list(df.columns.values)
print(columns, '\n')

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

['survived', 'pclass', 'sex', 'age']

In [14]:
columns_sorted = sorted(columns)
df_sorted = df[columns_sorted]
print(df_sorted, '\n')

    age  pclass     sex  survived
0  22.0       3    male         0
1  38.0       1  female         1
2  26.0       3  female         1
3  35.0       1  female         1
4  35.0       3    male         0

In [15]:
columns_reversed = list(reversed(columns))
df_reversed = df[columns_reversed]
print(df_reversed, '\n')

    age     sex  pclass  survived
0  22.0    male       3         0
1  38.0  female       1         1
2  26.0  female       3         1
3  35.0  female       1         1
4  35.0    male       3         0

In [16]:
columns_customed = ['pclass','sex','age','survived']
df_customed = df[columns_customed]
print(df_customed, '\n')

   pclass     sex   age  survived
0       3    male  22.0         0
1       1  female  38.0         1
2       3  female  26.0         1
3       1  female  35.0         1
4       3    male  35.0         0

In [17]:
import pandas as pd

df = pd.read_excel('./주가데이터.xlsx')
print(df.head(), '\n')
print(df.dtypes, '\n')

         연월일   당일종가  전일종가     시가     고가     저가     거래량
0 2018-07-02  10100   600  10850  10900  10000  137977
1 2018-06-29  10700   300  10550  10900   9990  170253
2 2018-06-28  10400   500  10900  10950  10150  155769
3 2018-06-27  10900   100  10800  11050  10500  133548
4 2018-06-26  10800   350  10900  11000  10700   63039

연월일     datetime64[ns]
당일종가             int64
전일종가             int64
시가               int64
고가               int64
저가               int64
거래량              int64
dtype: object

In [18]:
df['연월일'] = df['연월일'].astype('str')
dates = df['연월일'].str.split('-')
print(dates.head(), '\n')

0    [2018, 07, 02]
1    [2018, 06, 29]
2    [2018, 06, 28]
3    [2018, 06, 27]
4    [2018, 06, 26]
Name: 연월일, dtype: object

In [19]:
type(dates)

pandas.core.series.Series

In [20]:
df['연'] = dates.str.get(0)
df['월'] = dates.str.get(1)
df['일'] = dates.str.get(2)
print(df.head())

          연월일   당일종가  전일종가     시가     고가     저가     거래량     연   월   일
0  2018-07-02  10100   600  10850  10900  10000  137977  2018  07  02
1  2018-06-29  10700   300  10550  10900   9990  170253  2018  06  29
2  2018-06-28  10400   500  10900  10950  10150  155769  2018  06  28
3  2018-06-27  10900   100  10800  11050  10500  133548  2018  06  27
4  2018-06-26  10800   350  10900  11000  10700   63039  2018  06  26

##  필터링
* 특정 조건식을 만족하는 원소만 따로 추출

* **Boolean indexing** : 참 거짓을 판별하여 (참, 거짓)값으로 구성된 시리즈를 반환, 

 DataFrame 객체[불린 시리즈]

In [21]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

mask1 = (titanic.age >=10) & (titanic.age <20)
df_teenage = titanic.loc[mask1, :]
print(df_teenage.head())

    survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
9          1       2  female  14.0      1      0   30.0708        C  Second
14         0       3  female  14.0      0      0    7.8542        S   Third
22         1       3  female  15.0      0      0    8.0292        Q   Third
27         0       1    male  19.0      3      2  263.0000        S   First
38         0       3  female  18.0      2      0   18.0000        S   Third

      who  adult_male deck  embark_town alive  alone
9   child       False  NaN    Cherbourg   yes  False
14  child       False  NaN  Southampton    no   True
22  child       False  NaN   Queenstown   yes   True
27    man        True    C  Southampton    no  False
38  woman       False  NaN  Southampton    no  False

In [22]:
mask2 = (titanic.age <10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2, :]
print(df_female_under10.head())

     survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
10          1       3  female  4.0      1      1  16.7000        S   Third
24          0       3  female  8.0      3      1  21.0750        S   Third
43          1       2  female  3.0      1      2  41.5792        C  Second
58          1       2  female  5.0      1      2  27.7500        S  Second
119         0       3  female  2.0      4      2  31.2750        S   Third

       who  adult_male deck  embark_town alive  alone
10   child       False    G  Southampton   yes  False
24   child       False  NaN  Southampton    no  False
43   child       False  NaN    Cherbourg   yes  False
58   child       False  NaN  Southampton   yes  False
119  child       False  NaN  Southampton    no  False

In [23]:
mask3 = (titanic.age <10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age','sex','alone']]
print(df_under10_morethan60.head())

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

# isin() 메소드
* 특정 값을 가진 행들을 따로 추출

In [24]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

pd.set_option('display.max_columns', 10)  #출력할 열의 갯수를 제한

mask3 = titanic['sibsp'] == 3
mask4 = titanic['sibsp'] == 4
mask5 = titanic['sibsp'] == 5
df_boolean = titanic[mask3 | mask4 | mask5]
print(df_boolean.head())

    survived  pclass     sex   age  sibsp  ...  adult_male  deck  embark_town  \
7          0       3    male   2.0      3  ...       False   NaN  Southampton
16         0       3    male   2.0      4  ...       False   NaN   Queenstown
24         0       3  female   8.0      3  ...       False   NaN  Southampton
27         0       1    male  19.0      3  ...        True     C  Southampton
50         0       3    male   7.0      4  ...       False   NaN  Southampton

   alive  alone
7     no  False
16    no  False
24    no  False
27    no  False
50    no  False

[5 rows x 15 columns]

In [25]:
isin_filter = titanic['sibsp'].isin([3,4,5])
df_isin = titanic[isin_filter]
print(df_isin.head())

    survived  pclass     sex   age  sibsp  ...  adult_male  deck  embark_town  \
7          0       3    male   2.0      3  ...       False   NaN  Southampton
16         0       3    male   2.0      4  ...       False   NaN   Queenstown
24         0       3  female   8.0      3  ...       False   NaN  Southampton
27         0       1    male  19.0      3  ...        True     C  Southampton
50         0       3    male   7.0      4  ...       False   NaN  Southampton

   alive  alone
7     no  False
16    no  False
24    no  False
27    no  False
50    no  False

[5 rows x 15 columns]

## 데이터 프레임 합치기
* concat() : 데이터를 이어 붙이는 개념
* merge()  : SQL의 join처럼 병합하는 개념
* join()

In [26]:
import pandas as pd
df1 = pd.DataFrame({'a':['a0','a1','a2','a3'],
                   'b':['b0','b1','b2','b3'],
                   'c':['c0','c1','c2','c3']},
                  index=[0,1,2,3])
df2 = pd.DataFrame({'a':['a2','a3','a4','a5'],
                   'b':['b2','b3','b4','b5'],
                   'c':['c2','c3','c4','c5'],
                   'd':['d2','d3','d4','d5']},
                  index=[2,3,4,5])
print(df1, '\n')
print(df2, '\n')

result1 = pd.concat([df1,df2])
print(result1, '\n')

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
2  a2  b2  c2   d2
3  a3  b3  c3   d3
4  a4  b4  c4   d4
5  a5  b5  c5   d5

In [27]:
result2 = pd.concat([df1,df2], ignore_index=True)
print(result2, '\n')

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [28]:
result3 = pd.concat([df1,df2], axis=1)
print(result3, '\n')

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5

In [29]:
result3_in = pd.concat([df1,df2], axis=1, join='inner')
print(result3_in, '\n')

    a   b   c   a   b   c   d
2  a2  b2  c2  a2  b2  c2  d2
3  a3  b3  c3  a3  b3  c3  d3

In [30]:
df2.head()

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [31]:
sr1 = pd.Series(['e0','e1','e2','e3'], name='e')
sr2 = pd.Series(['f0','f1','f2'], name='f', index=[3,4,5])
sr3 = pd.Series(['g0','g1','g2','g3'], name='g')

result4 = pd.concat([df1,sr1], axis=1)
print(result4, '\n')

result5 = pd.concat([df2, sr2], axis=1, sort=True)
print(result5, '\n')

    a   b   c   e
0  a0  b0  c0  e0
1  a1  b1  c1  e1
2  a2  b2  c2  e2
3  a3  b3  c3  e3

    a   b   c   d    f
2  a2  b2  c2  d2  NaN
3  a3  b3  c3  d3   f0
4  a4  b4  c4  d4   f1
5  a5  b5  c5  d5   f2

In [32]:
result6 = pd.concat([sr1, sr3], axis=1)
print(result6, '\n')

result7 = pd.concat([sr1, sr3], axis=0)
print(result7, '\n')

    e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

## 데이터프레임 병합
* **merge()** 는 기준이 되는 열이나 인덱스를 Key라고 부르고 반드시 양쪽 데이터프레임에 모두 존재해야 한다.
* pandas.merge(df_left, df_right, how='inner', on='None')

In [33]:
import pandas as pd

pd.set_option('display.max_columns', 10) # 출력할 최대 열의 개수
pd.set_option('display.max_colwidth', 30)# 출력할 열의 너비
pd.set_option('display.unicode.east_asian_width', True) # 유니코드 사용 너비 조정

df1 = pd.read_excel('./stock price.xlsx')
df2 = pd.read_excel('./stock valuation.xlsx')

print(df1)
print('\n')
print(df2)

       id    stock_name          value   price
0  128940      한미약품   59385.666667  421000
1  130960        CJ E&M   58540.666667   98900
2  138250    엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280  녹십자엠에스     468.833333   10200
5  145990        삼양사   82750.000000   82000
6  185750        종근당   40293.666667  100500
7  192400    쿠쿠홀딩스  179204.666667  177500
8  199800          툴젠   -2514.333333  115400
9  204210  모두투어리츠    3093.333333    3475


       id              name           eps     bps        per       pbr
0  130960            CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480              하림    274.166667    3551  11.489362  0.887074
2  138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480            이마트  18268.166667  295780  13.931338  0.860437
4  145990            삼양사   5741.000000  108090  14.283226  0.758627
5  161390        한국타이어   5648.500000   51341   7.453306  0.820007
6  181710   NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
7  185750            종근당   3990.333333   40684  25.185866  2.470259
8  204210      모두투어리츠     85.166667    5335  40.802348  0.651359
9  207940  삼성바이오로직스   4644.166667   60099  89.790059  6.938551

* **on=None** : 두 데이터 프레임에 **공통으로 속하는 모든 열**을 기준(키)로 병합한다는 뜻
* **how='inner'** : 기준이 되는 **열의 데이터**가 양쪽 데이터프레임에 **공통으로 존재하는 교집합**일 경우 추출한다

In [34]:
# 기본값은 on=None, how='inner
merge_inner = pd.merge(df1, df2)
print(merge_inner)

       id    stock_name          value   price          name           eps  \
0  130960        CJ E&M   58540.666667   98900        CJ E&M   6301.333333
1  139480        이마트  239230.833333  254500        이마트  18268.166667
2  145990        삼양사   82750.000000   82000        삼양사   5741.000000
3  185750        종근당   40293.666667  100500        종근당   3990.333333
4  204210  모두투어리츠    3093.333333    3475  모두투어리츠     85.166667

      bps        per       pbr
0   54068  15.695091  1.829178
1  295780  13.931338  0.860437
2  108090  14.283226  0.758627
3   40684  25.185866  2.470259
4    5335  40.802348  0.651359

In [35]:
# 합집합
merge_outer = pd.merge(df1, df2, how='outer', on='id')
print(merge_outer)

        id    stock_name          value     price              name  \
0   128940      한미약품   59385.666667  421000.0               NaN
1   130960        CJ E&M   58540.666667   98900.0            CJ E&M
2   138250    엔에스쇼핑   14558.666667   13200.0               NaN
3   139480        이마트  239230.833333  254500.0            이마트
4   142280  녹십자엠에스     468.833333   10200.0               NaN
5   145990        삼양사   82750.000000   82000.0            삼양사
6   185750        종근당   40293.666667  100500.0            종근당
7   192400    쿠쿠홀딩스  179204.666667  177500.0               NaN
8   199800          툴젠   -2514.333333  115400.0               NaN
9   204210  모두투어리츠    3093.333333    3475.0      모두투어리츠
10  136480           NaN            NaN       NaN              하림
11  138040           NaN            NaN       NaN    메리츠금융지주
12  161390           NaN            NaN       NaN        한국타이어
13  181710           NaN            NaN       NaN   NHN엔터테인먼트
14  207940           NaN            NaN       NaN  삼성바이오로직스

             eps       bps        per       pbr
0            NaN       NaN        NaN       NaN
1    6301.333333   54068.0  15.695091  1.829178
2            NaN       NaN        NaN       NaN
3   18268.166667  295780.0  13.931338  0.860437
4            NaN       NaN        NaN       NaN
5    5741.000000  108090.0  14.283226  0.758627
6    3990.333333   40684.0  25.185866  2.470259
7            NaN       NaN        NaN       NaN
8            NaN       NaN        NaN       NaN
9      85.166667    5335.0  40.802348  0.651359
10    274.166667    3551.0  11.489362  0.887074
11   2122.333333   14894.0   6.313806  0.899691
12   5648.500000   51341.0   7.453306  0.820007
13   2110.166667   78434.0  30.755864  0.827447
14   4644.166667   60099.0  89.790059  6.938551

In [36]:
merge_left = pd.merge(df1, df2, how='left', left_on='stock_name', right_on='name')
print(merge_left)

     id_x    stock_name          value   price      id_y          name  \
0  128940      한미약품   59385.666667  421000       NaN           NaN
1  130960        CJ E&M   58540.666667   98900  130960.0        CJ E&M
2  138250    엔에스쇼핑   14558.666667   13200       NaN           NaN
3  139480        이마트  239230.833333  254500  139480.0        이마트
4  142280  녹십자엠에스     468.833333   10200       NaN           NaN
5  145990        삼양사   82750.000000   82000  145990.0        삼양사
6  185750        종근당   40293.666667  100500  185750.0        종근당
7  192400    쿠쿠홀딩스  179204.666667  177500       NaN           NaN
8  199800          툴젠   -2514.333333  115400       NaN           NaN
9  204210  모두투어리츠    3093.333333    3475  204210.0  모두투어리츠

            eps       bps        per       pbr
0           NaN       NaN        NaN       NaN
1   6301.333333   54068.0  15.695091  1.829178
2           NaN       NaN        NaN       NaN
3  18268.166667  295780.0  13.931338  0.860437
4           NaN       NaN        NaN       NaN
5   5741.000000  108090.0  14.283226  0.758627
6   3990.333333   40684.0  25.185866  2.470259
7           NaN       NaN        NaN       NaN
8           NaN       NaN        NaN       NaN
9     85.166667    5335.0  40.802348  0.651359

In [41]:
merge_right = pd.merge(df1, df2, how='right', left_on='stock_name', right_on='name').sort_values(by='id_x')
print(merge_right)

       id_x    stock_name          value     price    id_y              name  \
0  130960.0        CJ E&M   58540.666667   98900.0  130960            CJ E&M
3  139480.0        이마트  239230.833333  254500.0  139480            이마트
4  145990.0        삼양사   82750.000000   82000.0  145990            삼양사
7  185750.0        종근당   40293.666667  100500.0  185750            종근당
8  204210.0  모두투어리츠    3093.333333    3475.0  204210      모두투어리츠
1       NaN           NaN            NaN       NaN  136480              하림
2       NaN           NaN            NaN       NaN  138040    메리츠금융지주
5       NaN           NaN            NaN       NaN  161390        한국타이어
6       NaN           NaN            NaN       NaN  181710   NHN엔터테인먼트
9       NaN           NaN            NaN       NaN  207940  삼성바이오로직스

            eps     bps        per       pbr
0   6301.333333   54068  15.695091  1.829178
3  18268.166667  295780  13.931338  0.860437
4   5741.000000  108090  14.283226  0.758627
7   3990.333333   40684  25.185866  2.470259
8     85.166667    5335  40.802348  0.651359
1    274.166667    3551  11.489362  0.887074
2   2122.333333   14894   6.313806  0.899691
5   5648.500000   51341   7.453306  0.820007
6   2110.166667   78434  30.755864  0.827447
9   4644.166667   60099  89.790059  6.938551

In [43]:
price = df1[df1['price']<50000]
print(price.head())
print('\n')

value = pd.merge(price, df2)
print(value)

       id    stock_name         value  price
2  138250    엔에스쇼핑  14558.666667  13200
4  142280  녹십자엠에스    468.833333  10200
9  204210  모두투어리츠   3093.333333   3475


       id    stock_name        value  price          name        eps   bps  \
0  204210  모두투어리츠  3093.333333   3475  모두투어리츠  85.166667  5335

         per       pbr
0  40.802348  0.651359

## 데이터프레임 결합
* join(): merge()함수를 기반으로 만들어졌기 때문에 기본 동작이 서로 비슷
* join 은 두 데이터프레임의 행 인덱스를 기준으로 결합하는 점이 merge와 다르다
* 하지만 on=keys 옵션을 설정하면 행 인덱스 대신에 다른 열을 기준으로 결합할 수 있다.

In [54]:
import pandas as pd

pd.set_option('display.max_columns', 10) # 출력할 최대 열의 개수
pd.set_option('display.max_colwidth', 20)# 출력할 열의 너비
pd.set_option('display.unicode.east_asian_width', True) # 유니코드 사용 너비 조정

df1 = pd.read_excel('./stock price.xlsx', index_col='id')
df2 = pd.read_excel('./stock valuation.xlsx', index_col='id')

df3 = df1.join(df2)
print(df3)

          stock_name          value   price          name           eps  \
id
128940      한미약품   59385.666667  421000           NaN           NaN
130960        CJ E&M   58540.666667   98900        CJ E&M   6301.333333
138250    엔에스쇼핑   14558.666667   13200           NaN           NaN
139480        이마트  239230.833333  254500        이마트  18268.166667
142280  녹십자엠에스     468.833333   10200           NaN           NaN
145990        삼양사   82750.000000   82000        삼양사   5741.000000
185750        종근당   40293.666667  100500        종근당   3990.333333
192400    쿠쿠홀딩스  179204.666667  177500           NaN           NaN
199800          툴젠   -2514.333333  115400           NaN           NaN
204210  모두투어리츠    3093.333333    3475  모두투어리츠     85.166667

             bps        per       pbr
id
128940       NaN        NaN       NaN
130960   54068.0  15.695091  1.829178
138250       NaN        NaN       NaN
139480  295780.0  13.931338  0.860437
142280       NaN        NaN       NaN
145990  108090.0  14.283226  0.758627
185750   40684.0  25.185866  2.470259
192400       NaN        NaN       NaN
199800       NaN        NaN       NaN
204210    5335.0  40.802348  0.651359

In [55]:
df4 = df1.join(df2, how='inner')
print(df4)

          stock_name          value   price          name           eps  \
id
130960        CJ E&M   58540.666667   98900        CJ E&M   6301.333333
139480        이마트  239230.833333  254500        이마트  18268.166667
145990        삼양사   82750.000000   82000        삼양사   5741.000000
185750        종근당   40293.666667  100500        종근당   3990.333333
204210  모두투어리츠    3093.333333    3475  모두투어리츠     85.166667

           bps        per       pbr
id
130960   54068  15.695091  1.829178
139480  295780  13.931338  0.860437
145990  108090  14.283226  0.758627
185750   40684  25.185866  2.470259
204210    5335  40.802348  0.651359