## 엑셀 파일 읽어서 DataFrame 만들기

In [297]:
import pandas as pd

# 인덱스를 지정해 시트 설정
df_sheet_index = pd.read_excel('./../../test/0. 전산실현황(서울특별시교육청).xlsx', sheet_name=1)
print(df_sheet_index)

   Unnamed: 0        Unnamed: 1       Unnamed: 2   Unnamed: 3 Unnamed: 4  \
0         NaN  정보자원(정보시스템) 현황조사              NaN          NaN        NaN
1         NaN               NaN              NaN          NaN        NaN
2         NaN               NaN              NaN          NaN        NaN
3         NaN            1.상위기관            2.기관명       3.전산실명   4.전산실 위치
4         NaN               NaN              NaN          NaN        NaN
5         NaN          서울특별시교육청  서울특별시교육청교육연구정보원  교수학습정보부 서버실      서울특별시
6         NaN          서울특별시교육청  서울특별시교육청교육연구정보원       종합전산센터      서울특별시
7         NaN          서울특별시교육청  서울특별시교육청교육연구정보원   정보자원재해복구센터      서울특별시

   Unnamed: 5   Unnamed: 6  Unnamed: 7 Unnamed: 8      Unnamed: 9  ...  \
0         NaN          NaN         NaN        NaN             NaN  ...
1         NaN          NaN         NaN        NaN             NaN  ...
2         NaN          NaN         NaN        NaN             NaN  ...
3  5.전산실 설립연도  6.전산실 소유 형태  7.전산실 운영부서   8.담당자 성명       9.담당자 연락처  ...
4         NaN          NaN         NaN        NaN             NaN  ...
5        2003         자가건물     교수학습정보부        안상각    02-2230-8526  ...
6        2008         자가건물      인프라운영과   탁준표, 김세현     02-399-9703  ...
7        2017         자가건물      인프라운영과   이해진, 유한호  02-3019-8183,4  ...

  Unnamed: 51 Unnamed: 52 Unnamed: 53 Unnamed: 54     Unnamed: 55  \
0         NaN         NaN         NaN         NaN             NaN
1         NaN         NaN         NaN         NaN             NaN
2         NaN         NaN         NaN         NaN             NaN
3         NaN         NaN         NaN         NaN  45.전산실 입구 CCTV
4           3         4.0         5.0           계             NaN
5           ○         NaN         NaN           1             미설치
6           ○         NaN         NaN           1              설치
7           O         NaN         NaN           1              설치

       Unnamed: 56    Unnamed: 57 Unnamed: 58 Unnamed: 59  \
0              NaN            NaN         NaN         NaN
1              NaN            NaN         NaN         NaN
2              NaN            NaN         NaN         NaN
3    46.전산실 내 CCTV  47.정보보호 교육 횟수   48.백본 이중화  49.스위치 이중화
4              NaN            NaN         NaN         NaN
5  3실 미설치\n1,2실 설치              1       이중화없음       일부이중화
6               설치              2       전체이중화       전체이중화
7               설치              1      이중화 없음       전체이중화

            Unnamed: 60
0                   NaN
1                   NaN
2                   NaN
3  50.통신케이블 패치코드 꼬리표 부착
4                   NaN
5                    부착
6                    부착
7                    부착

[8 rows x 61 columns]

In [298]:
# skiprows=[0,1,2]를 이용하여 0,1,2 행을 제외하고 읽어온다
df_sheet_index = pd.read_excel('./../../test/0. 전산실현황(서울특별시교육청).xlsx', sheet_name=1, skiprows=[0,1,2])
print(df_sheet_index)

   Unnamed: 0 Unnamed: 1       Unnamed: 2   Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0         NaN     1.상위기관            2.기관명       3.전산실명   4.전산실 위치  5.전산실 설립연도
1         NaN        NaN              NaN          NaN        NaN         NaN
2         NaN   서울특별시교육청  서울특별시교육청교육연구정보원  교수학습정보부 서버실      서울특별시        2003
3         NaN   서울특별시교육청  서울특별시교육청교육연구정보원       종합전산센터      서울특별시        2008
4         NaN   서울특별시교육청  서울특별시교육청교육연구정보원   정보자원재해복구센터      서울특별시        2017

    Unnamed: 6  Unnamed: 7 Unnamed: 8      Unnamed: 9  ... Unnamed: 51  \
0  6.전산실 소유 형태  7.전산실 운영부서   8.담당자 성명       9.담당자 연락처  ...         NaN
1          NaN         NaN        NaN             NaN  ...           3
2         자가건물     교수학습정보부        안상각    02-2230-8526  ...           ○
3         자가건물      인프라운영과   탁준표, 김세현     02-399-9703  ...           ○
4         자가건물      인프라운영과   이해진, 유한호  02-3019-8183,4  ...           O

  Unnamed: 52 Unnamed: 53 Unnamed: 54     Unnamed: 55      Unnamed: 56  \
0         NaN         NaN         NaN  45.전산실 입구 CCTV    46.전산실 내 CCTV
1         4.0         5.0           계             NaN              NaN
2         NaN         NaN           1             미설치  3실 미설치\n1,2실 설치
3         NaN         NaN           1              설치               설치
4         NaN         NaN           1              설치               설치

     Unnamed: 57 Unnamed: 58 Unnamed: 59           Unnamed: 60
0  47.정보보호 교육 횟수   48.백본 이중화  49.스위치 이중화  50.통신케이블 패치코드 꼬리표 부착
1            NaN         NaN         NaN                   NaN
2              1       이중화없음       일부이중화                    부착
3              2       전체이중화       전체이중화                    부착
4              1      이중화 없음       전체이중화                    부착

[5 rows x 61 columns]

# 이름으로 지정
pd.read_excel('파일명.xlsx', usecols = ['사용할열_1', '사용할열_2'])

# 번호로 지정
pd.read_excel('파일명.xlsx', usecols = [0, 1])

In [323]:
# 필요한 컬럼만 지정해서 가져온다.
df_sheet_index = pd.read_excel('./../../test/0. 전산실현황(서울특별시교육청).xlsx', sheet_name=1
                               ,skiprows=[0,1,2], usecols="B:BI")
print(df_sheet_index)

  Unnamed: 1       Unnamed: 2   Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0     1.상위기관            2.기관명       3.전산실명   4.전산실 위치  5.전산실 설립연도
1        NaN              NaN          NaN        NaN         NaN
2   서울특별시교육청  서울특별시교육청교육연구정보원  교수학습정보부 서버실      서울특별시        2003
3   서울특별시교육청  서울특별시교육청교육연구정보원       종합전산센터      서울특별시        2008
4   서울특별시교육청  서울특별시교육청교육연구정보원   정보자원재해복구센터      서울특별시        2017

    Unnamed: 6  Unnamed: 7 Unnamed: 8      Unnamed: 9     Unnamed: 10  ...  \
0  6.전산실 소유 형태  7.전산실 운영부서   8.담당자 성명       9.담당자 연락처  10.정보시스템 운영 형태  ...
1          NaN         NaN        NaN             NaN             NaN  ...
2         자가건물     교수학습정보부        안상각    02-2230-8526            혼합운영  ...
3         자가건물      인프라운영과   탁준표, 김세현     02-399-9703            자체운영  ...
4         자가건물      인프라운영과   이해진, 유한호  02-3019-8183,4            자체운영  ...

  Unnamed: 51 Unnamed: 52 Unnamed: 53 Unnamed: 54     Unnamed: 55  \
0         NaN         NaN         NaN         NaN  45.전산실 입구 CCTV
1           3         4.0         5.0           계             NaN
2           ○         NaN         NaN           1             미설치
3           ○         NaN         NaN           1              설치
4           O         NaN         NaN           1              설치

       Unnamed: 56    Unnamed: 57 Unnamed: 58 Unnamed: 59  \
0    46.전산실 내 CCTV  47.정보보호 교육 횟수   48.백본 이중화  49.스위치 이중화
1              NaN            NaN         NaN         NaN
2  3실 미설치\n1,2실 설치              1       이중화없음       일부이중화
3               설치              2       전체이중화       전체이중화
4               설치              1      이중화 없음       전체이중화

            Unnamed: 60
0  50.통신케이블 패치코드 꼬리표 부착
1                   NaN
2                    부착
3                    부착
4                    부착

[5 rows x 60 columns]

In [324]:
# 행열 바꾸기
df_tx = df_sheet_index.transpose()
df_tx.head()

                     0    1                2                3                4
Unnamed: 1      1.상위기관  NaN         서울특별시교육청         서울특별시교육청         서울특별시교육청
Unnamed: 2       2.기관명  NaN  서울특별시교육청교육연구정보원  서울특별시교육청교육연구정보원  서울특별시교육청교육연구정보원
Unnamed: 3      3.전산실명  NaN      교수학습정보부 서버실           종합전산센터       정보자원재해복구센터
Unnamed: 4    4.전산실 위치  NaN            서울특별시            서울특별시            서울특별시
Unnamed: 5  5.전산실 설립연도  NaN             2003             2008             2017

In [325]:
# 컬럼지정하기
from pandas import DataFrame
df_col= DataFrame(df_tx)
df_col=df_col.rename(columns={0: '구분1', 1: '구분2', 2:'교수학습정보부', 3:'종합전산센터', 4:'재해복구센터'})
df_col[48:55]

                              구분1  구분2 교수학습정보부 종합전산센터 재해복구센터
Unnamed: 49  44.보안 설비의 유형 [중복 선택]    1     NaN    NaN    NaN
Unnamed: 50                   NaN    2     NaN    NaN    NaN
Unnamed: 51                   NaN    3       ○      ○      O
Unnamed: 52                   NaN    4     NaN    NaN    NaN
Unnamed: 53                   NaN    5     NaN    NaN    NaN
Unnamed: 54                   NaN    계       1      1      1
Unnamed: 55        45.전산실 입구 CCTV  NaN     미설치     설치     설치

In [326]:
# 결측치 채우기 (50번~54까지가 NaN으로 되어 있음) - 앞의 값으로 채움
import numpy as np 

df_col['구분1'].fillna(method='ffill', inplace=True)
df_col[48:55]

                              구분1  구분2 교수학습정보부 종합전산센터 재해복구센터
Unnamed: 49  44.보안 설비의 유형 [중복 선택]    1     NaN    NaN    NaN
Unnamed: 50  44.보안 설비의 유형 [중복 선택]    2     NaN    NaN    NaN
Unnamed: 51  44.보안 설비의 유형 [중복 선택]    3       ○      ○      O
Unnamed: 52  44.보안 설비의 유형 [중복 선택]    4     NaN    NaN    NaN
Unnamed: 53  44.보안 설비의 유형 [중복 선택]    5     NaN    NaN    NaN
Unnamed: 54  44.보안 설비의 유형 [중복 선택]    계       1      1      1
Unnamed: 55        45.전산실 입구 CCTV  NaN     미설치     설치     설치

In [327]:
# 구분2의 NaN 를 스페이스로 변경하기
df_col['구분2'].replace(np.NaN, '', inplace=True)
df_col[54:55]

                        구분1 구분2 교수학습정보부 종합전산센터 재해복구센터
Unnamed: 55  45.전산실 입구 CCTV         미설치     설치     설치

In [328]:
# 컬럼의 타입을 string 으로 각각 변경한다.
# df_col[['구분1', '구분2']].astype(str)
df_col[19:28]

                              구분1  구분2                교수학습정보부 종합전산센터 재해복구센터
Unnamed: 20       20.전산실 장애/재해 빈도                          23      6      0
Unnamed: 21       21.장애 발생 시간(연간)       200\n(shutdown 5.5시간)     27      0
Unnamed: 22        22.ShutDown 빈도                           1      0      0
Unnamed: 23  23.보유한 자동화 툴 [중복 선택]  SMS                      -      ○    NaN
Unnamed: 24  23.보유한 자동화 툴 [중복 선택]  NMS                      -      ○    NaN
Unnamed: 25  23.보유한 자동화 툴 [중복 선택]  ESM                      -      ○    NaN
Unnamed: 26  23.보유한 자동화 툴 [중복 선택]  FMS                      -      ○      ○
Unnamed: 27  23.보유한 자동화 툴 [중복 선택]   기타                      -      ○    NaN
Unnamed: 28  23.보유한 자동화 툴 [중복 선택]    계                      0      5      1

In [329]:
# 컬럼 값을 합치기
df_col['구분']=df_col['구분1'].str.cat(df_col['구분2'].astype(str))
df_col[19:28]

,구분1,구분2,교수학습정보부,종합전산센터,재해복구센터,구분
Unnamed: 20,20.전산실 장애/재해 빈도,,23,6,0,20.전산실 장애/재해 빈도
Unnamed: 21,21.장애 발생 시간(연간),,200\n(shutdown 5.5시간),27,0,21.장애 발생 시간(연간)
Unnamed: 22,22.ShutDown 빈도,,1,0,0,22.ShutDown 빈도
Unnamed: 23,23.보유한 자동화 툴 [중복 선택],SMS,-,○,NaN,23.보유한 자동화 툴 [중복 선택]SMS
Unnamed: 24,23.보유한 자동화 툴 [중복 선택],NMS,-,○,NaN,23.보유한 자동화 툴 [중복 선택]NMS
Unnamed: 25,23.보유한 자동화 툴 [중복 선택],ESM,-,○,NaN,23.보유한 자동화 툴 [중복 선택]ESM
Unnamed: 26,23.보유한 자동화 툴 [중복 선택],FMS,-,○,○,23.보유한 자동화 툴 [중복 선택]FMS
Unnamed: 27,23.보유한 자동화 툴 [중복 선택],기타,-,○,NaN,23.보유한 자동화 툴 [중복 선택]기타
Unnamed: 28,23.보유한 자동화 툴 [중복 선택],계,0,5,1,23.보유한 자동화 툴 [중복 선택]계

In [330]:
# 인덱스를 지정한다.
df_col.set_index(df_col.구분, inplace=True)
df_col[19:28]

,구분1,구분2,교수학습정보부,종합전산센터,재해복구센터,구분
구분,,,,,,
20.전산실 장애/재해 빈도,20.전산실 장애/재해 빈도,,23,6,0,20.전산실 장애/재해 빈도
21.장애 발생 시간(연간),21.장애 발생 시간(연간),,200\n(shutdown 5.5시간),27,0,21.장애 발생 시간(연간)
22.ShutDown 빈도,22.ShutDown 빈도,,1,0,0,22.ShutDown 빈도
23.보유한 자동화 툴 [중복 선택]SMS,23.보유한 자동화 툴 [중복 선택],SMS,-,○,NaN,23.보유한 자동화 툴 [중복 선택]SMS
23.보유한 자동화 툴 [중복 선택]NMS,23.보유한 자동화 툴 [중복 선택],NMS,-,○,NaN,23.보유한 자동화 툴 [중복 선택]NMS
23.보유한 자동화 툴 [중복 선택]ESM,23.보유한 자동화 툴 [중복 선택],ESM,-,○,NaN,23.보유한 자동화 툴 [중복 선택]ESM
23.보유한 자동화 툴 [중복 선택]FMS,23.보유한 자동화 툴 [중복 선택],FMS,-,○,○,23.보유한 자동화 툴 [중복 선택]FMS
23.보유한 자동화 툴 [중복 선택]기타,23.보유한 자동화 툴 [중복 선택],기타,-,○,NaN,23.보유한 자동화 툴 [중복 선택]기타
23.보유한 자동화 툴 [중복 선택]계,23.보유한 자동화 툴 [중복 선택],계,0,5,1,23.보유한 자동화 툴 [중복 선택]계

In [331]:
# 필요없는 컬럼을 지운다. axis row:0  column:1
df_col=df_col.drop(['구분1','구분2','구분'], axis=1) 
df_col[19:28]

                                       교수학습정보부 종합전산센터 재해복구센터
구분
20.전산실 장애/재해 빈도                             23      6      0
21.장애 발생 시간(연간)          200\n(shutdown 5.5시간)     27      0
22.ShutDown 빈도                               1      0      0
23.보유한 자동화 툴 [중복 선택]SMS                      -      ○    NaN
23.보유한 자동화 툴 [중복 선택]NMS                      -      ○    NaN
23.보유한 자동화 툴 [중복 선택]ESM                      -      ○    NaN
23.보유한 자동화 툴 [중복 선택]FMS                      -      ○      ○
23.보유한 자동화 툴 [중복 선택]기타                       -      ○    NaN
23.보유한 자동화 툴 [중복 선택]계                        0      5      1