In [1]:
import urllib.request
client_id = ""
client_secret = ""

* urllib.parse.quote : parameter를 utf-8로 인코딩하여 리턴

In [2]:
encText = urllib.parse.quote("pinkwink")
url = "https://openapi.naver.com/v1/search/blog.json?query=" + encText
url

'https://openapi.naver.com/v1/search/blog.json?query=pinkwink'

In [5]:
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id", client_id)
request.add_header("X-Naver-Client-Secret", client_secret)

In [6]:
response = urllib.request.urlopen(request)
print(response.getcode())

200

In [7]:
type(response)

http.client.HTTPResponse

In [8]:
print(response.read().decode('utf-8'))

{
"lastBuildDate": "Sun, 26 Jul 2020 21:28:49 +0900",
"total": 1875,
"start": 1,
"display": 10,
"items": [
{
"title": "<b>PinkWink</b> 블로그에서 온 선물..",
"link": "https:\/\/blog.naver.com\/chandong83?Redirect=Log&logNo=221531853244",
"description": "국내 최고 아이티 블로그인 <b>PinkWink</b> 블로거이신 민형기 박사님께서 선물을 보내주셨다~ 크.. 이런 영광이!!!! 잘 쓰겠습니다~ 박사님!!! 나도 나중에 블로그 잘 운영해서 이런 선물도 나눠줘 보고 싶다~~ㅋ 요즘... ",
"bloggername": "하이! 제니스",
"bloggerlink": "https://blog.naver.com/chandong83",
"postdate": "20190507"

},
{
"title": "Project -ing) <b>PinkWink</b> (핑크윙크) 쇼핑몰 브랜드 로고디자인... ",
"link": "https:\/\/blog.naver.com\/honggraphic?Redirect=Log&logNo=221880867448",
"description": "한국브랜드에 대한 위상이 높아지고 있는 요즘, K를 강조한 브랜드 개발 요청이 많아지고 있습니다. 이번 프로젝트는 쇼핑몰 브랜드로 베트남과 말레이시아 등의 수출을 목표로 한류 열풍을 이어나갈... ",
"bloggername": "홍그래픽",
"bloggerlink": "https://blog.naver.com/honggraphic",
"postdate": "20200330"

},
{
"title": "2019년 <b>PinkWink</b> 블로그 결산",
"link": "https://pinkwink.kr/1259?category=92396",
"description": "^^. 저는 크리스마스때 괌으로 떠나서 올해는 거기서 보낼 예정입니다. 다들 새해 복 많이 많으시구요. 우리는 다시 내년에 만나요~~~^^ 좋아요 13 공유하기 글 요소 구독하기 <b>PinkWink</b> 저작자표시",
"bloggername": "PinkWink",
"bloggerlink": "https://pinkwink.kr/",
"postdate": "20191223"

},
{
"title": "[공유] <b>PinkWink</b> :: 저역통과필터와 고역통과필터를 C로 구현",
"link": "https:\/\/blog.naver.com\/kangusreport?Redirect=Log&logNo=221870399107",
"description": "<b>PinkWink</b> :: 저역통과필터와 고역통과필터를 C로 구현",
"bloggername": "Dex Note",
"bloggerlink": "https://blog.naver.com/kangusreport",
"postdate": "20200324"

},
{
"title": "[<b>pinkwink</b>님-구매후기]",
"link": "https:\/\/blog.naver.com\/monetchou?Redirect=Log&logNo=150182740062",
"description": "친구들 중에 강아지 키우는 아이들에겐 연말선물로 강아지옷선물했는데. 이옷너무 이쁘다고.맘에 든다고 해주어서 저도 으쓱해졌습니다. 옷입고 포즈도 잘취해주고.귀엽죠? 덕분에...저... ",
"bloggername": "몽에슈",
"bloggerlink": "https://blog.naver.com/monetchou",
"postdate": "20140110"

},
{
"title": "[공유] <b>PinkWink</b> :: 맥에서 윈도우용(NTFS) 외장하드에 파일... ",
"link": "https:\/\/blog.naver.com\/sonidda?Redirect=Log&logNo=221722293907",
"description": "<b>PinkWink</b> :: 맥에서 윈도우용(NTFS) 외장하드에 파일 복사/쓰기 가능하게 해주는 Mounty",
"bloggername": "손스의 소소한 기록들",
"bloggerlink": "https://blog.naver.com/sonidda",
"postdate": "20191129"

},
{
"title": "<b>PinkWink</b>님의 미바뤼 돌촬영 후기 :)",
"link": "https:\/\/blog.naver.com\/creta01?Redirect=Log&logNo=220191244266",
"description": "원본출처 : <b>PinkWink</b>님 블로그 :) http://<b>pinkwink</b>.kr/678",
"bloggername": "A moment in life",
"bloggerlink": "https://blog.naver.com/creta01",
"postdate": "20141125"

},
{
"title": "<b>PinkWink</b> :: 정보를 담고 있는 좌표계에 회전행렬을 적용하는... ",
"link": "http://blog.daum.net/knightofelf/42100",
"description": "<b>PinkWink</b> :: 정보를 담고 있는 좌표계에 회전행렬을 적용하는 방법 http://<b>pinkwink</b>.kr/404",
"bloggername": "knight of elf - 애들은 잘놀아",
"bloggerlink": "http://blog.daum.net/knightofelf",
"postdate": "20190930"

},
{
"title": "http://<b>pinkwink</b>.kr/218",
"link": "https:\/\/blog.naver.com\/2danzee?Redirect=Log&logNo=220548423642",
"description": "http://<b>pinkwink</b>.kr/218",
"bloggername": "2danzee님의블로그",
"bloggerlink": "https://blog.naver.com/2danzee",
"postdate": "20151124"

},
{
"title": "고유값과 고유벡터, 그리고 직교행렬 - http://<b>pinkwink</b>.kr/",
"link": "https://economicslab.tistory.com/12064",
"description": "http://<b>pinkwink</b>.kr/185 좋아요 공감 공유하기 글 요소 구독하기 Jaeseong's Infinite Post! 재성이의 무한 포스트! 저작자표시 비영리 변경금지",
"bloggername": "Jaeseong's Infinite Post! 재성이의 무한 포스트!",
"bloggerlink": "http://economicslab.tistory.com/",
"postdate": "20120925"

}
]
}

In [9]:
for n in [1,2,3]:
    print(n)

1
2
3

In [10]:
for n in [1,2,3,4,5]:
    print(n**2)

1
4
9
16
25

In [11]:
[n**2 for n in range(1,6)]

[1, 4, 9, 16, 25]

In [12]:
def get_square(n):
    return n**2

In [13]:
[get_square(n) for n in [1,2,3,4]]

[1, 4, 9, 16]

In [19]:
def create_url(api_node, search_text, start_num, disp_num):
    base = "https://openapi.naver.com/v1/search"
    node = "/" + api_node + ".json"
    param_query = "?query=" + urllib.parse.quote(search_text)
    param_start = "&start=" + str(start_num)
    param_disp = "&display=" + str(disp_num)
    
    return base + node + param_query + param_start + param_disp

In [20]:
create_url("book", "TEST", 1, 10)

'https://openapi.naver.com/v1/search/book.json?query=TEST&start=1&display=10'

In [21]:
import json

url = create_url("book", "파이썬", 1, 3)

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id", client_id)
request.add_header("X-Naver-Client-Secret", client_secret)

response = urllib.request.urlopen(request)

result = json.loads(response.read().decode('utf-8'))
result

{'lastBuildDate': 'Sun, 26 Jul 2020 21:49:29 +0900',
 'total': 1088,
 'start': 1,
 'display': 3,
 'items': [{'title': '혼자 공부하는 <b>파이썬</b> (<b>파이썬</b> 최신 버전 반영)',
   'link': 'http://book.naver.com/bookdb/book_detail.php?bid=15028688',
   'image': 'https://bookthumb-phinf.pstatic.net/cover/150/286/15028688.jpg?type=m1&udate=20200321',
   'author': '윤인성',
   'price': '18000',
   'discount': '16200',
   'publisher': '한빛미디어',
   'pubdate': '20190610',
   'isbn': '1162241888 9791162241882',
   'description': '1:1 과외하듯 배우는 <b>파이썬</b> 프로그래밍 자습서(<b>파이썬</b> 최신 버전 반영)\n이 책은 독학으로 프로그래밍 언어를 처음 배우려는 입문자가, 혹은 <b>파이썬</b>을 배우려는 입문자가 ‘꼭 필요한 내용을 제대로’ 학습할 수 있도록 구성했다. ‘무엇을’, ‘어떻게’ 학습해야 할지조차 모르는 입문자의 막연한 마음을 살펴... '},
  {'title': 'Do it! 점프 투 <b>파이썬</b>',
   'link': 'http://book.naver.com/bookdb/book_detail.php?bid=15052904',
   'image': 'https://bookthumb-phinf.pstatic.net/cover/150/529/15052904.jpg?type=m1&udate=20200418',
   'author': '박응용',
   'price': '18800',
   'discount': '16920',
   'publisher': '이지스퍼블리싱',
   'pubdate': '20190620',
   'isbn': '1163030910 9791163030911',
   'description': '<b>파이썬</b> 4년 연속 베스트셀러 1위! ★★★★\n《DO IT! 점프 투 <b>파이썬</b>》 전면 개정판 출시!\n문과생도 중고등학생도 직장인도 프로그래밍에 눈뜨게 만든... 점프 투 <b>파이썬</b>》으로 출간되었던 이 책은 약 4년 동안의 피드백을 반영하여 초보자가 더 빠르게 입문하고, 더 깊이 있게 공부할 수 있도록 개정되었다.... '},
  {'title': '<b>파이썬</b> 증권 데이터 분석 (<b>파이썬</b> 입문, 웹 스크레이핑, 트레이딩 전략, 자동 매매)',
   'link': 'http://book.naver.com/bookdb/book_detail.php?bid=16381920',
   'image': 'https://bookthumb-phinf.pstatic.net/cover/163/819/16381920.jpg?type=m1&udate=20200723',
   'author': '김황후',
   'price': '32000',
   'discount': '28800',
   'publisher': '한빛미디어',
   'pubdate': '20200701',
   'isbn': '1162243201 9791162243206',
   'description': '투자 기법과 프로그래밍 기술로 \n자신만의 퀀트 투자 시스템을 완성하라\n이 책은 웹 스크레이핑으로 증권 데이터를 주기적으로 자동 수집, 분석, 자동 매매, 예측하는 전 과정을 <b>파이썬</b>으로 직접 구현한다. 그 과정에서 금융 데이터 처리 기본 라이브러리(팬더스)부터 주가 예측에 딥러닝 라이브러리(텐서플로)까지... '}]}

In [22]:
len(result['items'])

3

In [23]:
titles = [result['items'][n]['title'] for n in range(3)]
titles

['혼자 공부하는 <b>파이썬</b> (<b>파이썬</b> 최신 버전 반영)',
 'Do it! 점프 투 <b>파이썬</b>',
 '<b>파이썬</b> 증권 데이터 분석 (<b>파이썬</b> 입문, 웹 스크레이핑, 트레이딩 전략, 자동 매매)']

In [24]:
authors = [result['items'][n]['author'] for n in range(3)]
authors

['윤인성', '박응용', '김황후']

In [27]:
pubdates = [result['items'][n]['pubdate'] for n in range(3)]
pubdates

['20190610', '20190620', '20200701']

In [28]:
import pandas as pd

pd.DataFrame({'책제목':titles, '작가':authors, '출판일':pubdates})

                                                 책제목   작가       출판일
0           혼자 공부하는 <b>파이썬</b> (<b>파이썬</b> 최신 버전 반영)  윤인성  20190610
1                             Do it! 점프 투 <b>파이썬</b>  박응용  20190620
2  <b>파이썬</b> 증권 데이터 분석 (<b>파이썬</b> 입문, 웹 스크레이핑, ...  김황후  20200701

In [31]:
def get_dataframe(url):
    client_id = "LP0JME3o423ZaDG2Q87G"
    client_secret = "yEzOfXxjgG"

    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)

    response = urllib.request.urlopen(request)

    result = json.loads(response.read().decode('utf-8'))

    end_num = result['display']
    
    titles = [result['items'][n]['title'] for n in range(end_num)]
    authors = [result['items'][n]['author'] for n in range(end_num)]
    pubdates = [result['items'][n]['pubdate'] for n in range(end_num)]
    
    return pd.DataFrame({'책제목':titles, '작가':authors, '출판일':pubdates})

In [32]:
get_dataframe(url)

                                                 책제목   작가       출판일
0           혼자 공부하는 <b>파이썬</b> (<b>파이썬</b> 최신 버전 반영)  윤인성  20190610
1                             Do it! 점프 투 <b>파이썬</b>  박응용  20190620
2  <b>파이썬</b> 증권 데이터 분석 (<b>파이썬</b> 입문, 웹 스크레이핑, ...  김황후  20200701

In [33]:
def delete_tag(input_str):
    input_str = input_str.replace("<b>","")
    input_str = input_str.replace("</b>","")
    return input_str

In [35]:
def get_dataframe(url):
    client_id = "LP0JME3o423ZaDG2Q87G"
    client_secret = "yEzOfXxjgG"

    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)

    response = urllib.request.urlopen(request)

    result = json.loads(response.read().decode('utf-8'))

    end_num = result['display']
    
    titles = [delete_tag(result['items'][n]['title']) for n in range(end_num)]
    authors = [delete_tag(result['items'][n]['author']) for n in range(end_num)]
    pubdates = [delete_tag(result['items'][n]['pubdate']) for n in range(end_num)]
    
    return pd.DataFrame({'책제목':titles, '작가':authors, '출판일':pubdates})

In [36]:
get_dataframe(url)

                                               책제목   작가       출판일
0                       혼자 공부하는 파이썬 (파이썬 최신 버전 반영)  윤인성  20190610
1                                  Do it! 점프 투 파이썬  박응용  20190620
2  파이썬 증권 데이터 분석 (파이썬 입문, 웹 스크레이핑, 트레이딩 전략, 자동 매매)  김황후  20200701

In [37]:
[n for n in range(1,300,100)]

[1, 101, 201]

In [38]:
result_search = []

for n in range(1,300,100):
    url = create_url("book","파이썬 ", n, 100)
    result_search.append(get_dataframe(url))
    
result_search = pd.concat(result_search)

In [39]:
result_search.head()

                                                 책제목   작가       출판일
0                         혼자 공부하는 파이썬 (파이썬 최신 버전 반영)  윤인성  20190610
1                                    Do it! 점프 투 파이썬  박응용  20190620
2    파이썬 증권 데이터 분석 (파이썬 입문, 웹 스크레이핑, 트레이딩 전략, 자동 매매)  김황후  20200701
3  파이썬 머신러닝 완벽 가이드 (다양한 캐글 예제와 함께 기초 알고리즘부터 최신 기법...  권철민  20200207
4        파이썬 알고리즘 인터뷰 (95가지 알고리즘 문제 풀이로 완성하는 코딩 테스트)  박상길  20200715

* info()결과에서 index가 0~99까지만 보인다. 반복문마다 index 가 매겨져서 0-99가 3번 있을 것이다
이것을 해결하기 위해 reset_index를 해준다.

In [40]:
result_search.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 0 to 99
Data columns (total 3 columns):
책제목    300 non-null object
작가     300 non-null object
출판일    300 non-null object
dtypes: object(3)
memory usage: 9.4+ KB

In [41]:
result_search = result_search.reset_index(drop=True)
result_search.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
책제목    300 non-null object
작가     300 non-null object
출판일    300 non-null object
dtypes: object(3)
memory usage: 7.1+ KB